### ISSUE TITLE
false positive rate detail

### ISSUE THREAD

**Issue by jrmxn** [markallenthornton/MatlabTFCE#4]
This is a technical detail with (probably) no repercursions but I am wondering if:

`sum(fp)/nsim % false positive rate
`
in the test scripts, should actually be:

`sum(fp>0)/nsim % false positive rate
`
Sorry for the nitpicking - just trying to clear up some confusion I was having.

Thanks

**Comment by markallenthornton** [comment]
Yes, you're quite right. I didn't notice before because the data in the demo are just random N(0,1) without any spatial smoothness, and so it's rare that there will be two false positives at the same time. Thus, the resulting bias was below the estimation precision when I ran the demos with small numbers of permutations/iterations. No repercussions for the package itself, as you expected. Thanks for catching this issue!

**Comment by jrmxn** [comment]
OK thanks - was playing around with introducing some smoothing and was confused for a minute!
